# Ease of Replication Strategy

Python, sourcing data, ETL constrains and logic. 

## Nuclear & Hydroelectric Energy Dummy Variables


## Country Sorting Algorithm

In our ETL process (Extract, Transform, Load) we are working on the premise that certain countries have better policies, cultural attitude towards alternative energy that make them more likely to have a turning point in the EKC.  If the goal is CO2 emmisions, other countries will seek proof of the existence of such policies to effectively enable such turning point, as every nation wishes to both maximize wealth and minize emmissions.  Thus, in spite of the potential critisism that this is an exercise in "fitting the data to the model", we feel it has value in a proper test of the existence of the EKC, as most academic literature to this date has failed to do this, either to poor selection of explanatory variables, or simply because the data available was too sparse or inaccurate.   

Data on wind power generation in Megawatts is available from Eurostat from 1990 to 2018, but only for very few countries. For some countries the data from early years is strangely replicated identically across years, almost as if a Windmill was built and remained the only unit in operation, then suddenly there is a ramp up. This is a suspicius pattern indeed, for example:

`
1991,"France","1.000"
1992,"France","1.000"
1993,"France","3.000"
1994,"France","3.000"
1995,"France","3.000"
`

We suspect that someone would really require historical domain expertise to enterprit such numbers as errouneous or valid. 

In analyzing EKC relationships this data may prove useful, especially if it can be tracked in Kilowatt per Capita by dividing yearly capacity by population for each country.  

The difficulty, however, lies in the fact that this data is highly suspect.   This section will outline what problems exist, and various potential ways to overcome it. 

I have experimented exstensively with data cleanup and manipulation in Stata, Excel with Visual Basic, R, and Python.  This section is meant to provide instructions to anyone who wishes to replicate this paper for future validation as more wind power data continues to become availabe in the future. This paper is specifically biased towards the immense power and flexibility of Python to deal with this type of data cleaning process, while pointing out some perculiar drawbacks of it's nearest rival R. 

### Technical Preliminaries

t an integrated set of data structures and
tools providing this functionality.


### Processing raw data from Eurostat

Raw wind data from Eurostat can be downloaded from all European countries in the following format:

In [69]:
from pandas import read_csv
df = read_csv('data/nrg_inf_epcrw_1_Data.csv')
df.head()

,TIME,GEO,SIEC,PLANT_TEC,UNIT,Value
0,1990,European Union - 27 countries (from 2020),Wind,Net maximum electrical capacity,Megawatt,443.981
1,1990,European Union - 28 countries (2013-2020),Wind,Net maximum electrical capacity,Megawatt,453.981
2,1990,Euro area - 19 countries (from 2015),Wind,Net maximum electrical capacity,Megawatt,110.000
3,1990,Belgium,Wind,Net maximum electrical capacity,Megawatt,5.000
4,1990,Bulgaria,Wind,Net maximum electrical capacity,Megawatt,:

### Drop Useless Columns & Rename Columns using Pipelines

See [this article from Nov 2019](https://towardsdatascience.com/https-medium-com-tirthajyoti-build-pipelines-with-pandas-using-pdpipe-cade6128cd31)

`
pipeline = pdp.ColDrop(‘Avg. Area House Age’)
pipeline+= pdp.OneHotEncode(‘House_size’)
df3 = pipeline(df)
`
Net maximum electrical capacity 	Megawatt 	is repeated but should be in the metadata.

In [72]:

def price_tag(x):
    if x>250000:
        return 'keep'
    else:
        return 'drop'

    
#value_map = {"Germany (until 1990 former territory of the FRG)": 'Germany'}
#! pip install pdpipe
import pdpipe as pdp
#  Creat some tasks without executing them
pipeline = pdp.ColDrop(['SIEC', 'PLANT_TEC', 'UNIT'])
pipeline+=pdp.RowDrop({'Value': lambda x: x ==':'})
pipeline+=pdp.RowDrop({'GEO': lambda x: str(x).find('Euro')==0}) # Find method finds the first Occurance place in string
pipeline+=pdp.RegexReplace('GEO', r'\(.*\)', "") # Remove parenthese and everything in between
#pipeline+=pdp.MapColVals('GEO', value_map)
# Now send add this tasks in a pipeline
df = pipeline(df)

#data = data.drop(columns=['SIEC', 'PLANT_TEC', 'UNIT'])
#data.pd.rename(columns = {'test':'TEST'}, inplace = True) 
df.head(300)

     TIME             GEO       Value
3    1990         Belgium       5.000
6    1990         Denmark     325.981
7    1990        Germany       48.000
10   1990          Greece       1.000
11   1990           Spain       2.000
14   1990           Italy       3.000
21   1990     Netherlands      50.000
24   1990        Portugal       1.000
29   1990          Sweden       8.000
30   1990  United Kingdom      10.000
46   1991         Belgium       5.000
49   1991         Denmark     392.859
50   1991        Germany      110.000
53   1991          Greece       1.000
54   1991           Spain       3.000
55   1991          France       1.000
57   1991           Italy       4.000
64   1991     Netherlands      83.000
67   1991        Portugal       1.000
71   1991         Finland       1.000
72   1991          Sweden      12.000
73   1991  United Kingdom      14.000
89   1992         Belgium       5.000
92   1992         Denmark     435.949
93   1992        Germany      183.000
95   1992         Ireland       6.500
96   1992          Greece      16.000
97   1992           Spain      33.000
98   1992          France       1.000
100  1992           Italy       7.000
..    ...             ...         ...
653  2005         Estonia      31.000
654  2005         Ireland     493.300
655  2005          Greece     491.000
656  2005           Spain   9,918.000
657  2005          France     690.000
658  2005         Croatia       6.000
659  2005           Italy   1,635.000
660  2005          Cyprus       0.225
661  2005          Latvia      26.000
662  2005       Lithuania       1.000
663  2005      Luxembourg      34.900
664  2005         Hungary      17.000
666  2005     Netherlands   1,224.000
667  2005         Austria     825.219
668  2005          Poland     121.000
669  2005        Portugal   1,064.000
670  2005         Romania       1.000
672  2005        Slovakia       5.000
673  2005         Finland      82.000
674  2005          Sweden     522.000
675  2005  United Kingdom   1,565.000
677  2005          Norway     265.000
682  2005          Turkey      21.000
686  2005         Ukraine      65.000
691  2006         Belgium     212.000
692  2006        Bulgaria      27.000
693  2006         Czechia      43.500
694  2006         Denmark   3,135.696
695  2006        Germany   20,474.000
696  2006         Estonia      31.000

[300 rows x 3 columns]

By immediate visual inspection it's obvious that much cleanup is required to make it useful for regression analysis.  


### Purge Useless Data

Ge

Eurostat has certain oddities that need to be removed:

`
"Germany (until 1990 former territory of the FRG)"
"Kosovo (under United Nations Security Council Resolution 1244/99)"
`

should both be chaned to "Germany" and "Kosovo".  It's odd that Eurostat does not include international ISO country codes in the data, as this is essential to merge  panel data sets various sources using universal country codes and years.

In [65]:
df = (
df
# clean column names
.rename(columns={'TIME': 'Year', 'GEO': 'Country', 'Value':'Megawatts'})
.dropna()
)
df.head()

AttributeError: 'DataFrame' object has no attribute 'rstrip'

In [59]:
x = "European String"

print(x.find('European String'))

0